language: julia
os:
    - osx
    - linux
julia:
    - 0.4
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("BVP"); Pkg.test("BVP"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("BVP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
